name: build-deploy-weather-api-on-dockerhub

run-name: ${{ github.actor }} is building a Docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and run hadolint
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.4.1/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint
          hadolint Dockerfile
      - name: Build docker image
        run: docker build . -t weatherapi:0.0.2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create docker image tag
        run: docker tag weatherapi:0.0.2 ${{ secrets.DOCKER_USER_REGISTRY }}/weatherapi:0.0.2
      - name: Push to docker hub
        run: docker push ${{ secrets.DOCKER_USER_REGISTRY }}/weatherapi:0.0.2